[package]
name = "ci-net"
description = "Network configuration model, parsers and renderers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
ci-config.workspace = true
ci-core.workspace = true
ci-log.workspace = true
ci-sys.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
