[package]
name = "ds-identify"
description = "Rust replacement for the ds-identify shell script"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
ci-sys.workspace = true

[[bin]]
name = "ds-identify"
path = "src/main.rs"
