"""Regenerates crates/ci-distro/src/table.rs from the packaged cloud-init."""
import json
from cloudinit import distros



UNIFORM = {
    "hosts_fn": "/etc/hosts",
    "doas_fn": "/etc/doas.conf",
    "shadow_extrausers_fn": "/var/lib/extrausers/shadow",
    "tz_zone_dir": "/usr/share/zoneinfo",
}


def rs(s):
    return json.dumps(s)


def opt(v):
    return "None" if v is None else "Some(%s)" % rs(v)


def slist(v):
    return "&[%s]" % ", ".join(rs(x) for x in v)


# Which `_write_hostname` a distro gets is read off the MRO rather than guessed
# from the family: the two do not agree (`azurelinux` is a `rhel` subclass but
# names itself in `osfamily`). The mapping and the lookup live in `distro.py`,
# so the generated table and the differential that checks it cannot drift.
from distro import (
    hostname_reader,
    hostname_writer,
    locale_reader,
    locale_writer,
    system_hostname_reader,
    timezone_writer,
    waits_for_network,
)


rows = []
for family, names in distros.OSFAMILIES.items():
    for name in names:
        try:
            # `net_convert.py` builds the object the same way; several
            # `__init__`s rewrite `renderer_configs` and one rewrites
            # `eni_path`, so the class attributes are not what a boot sees.
            # The cfg dict is kept because several `__init__`s write
            # `ssh_svcname` into it, and `get_option` reads it back out.
            cfg = {}
            cls = distros.fetch(name)(name, cfg, None)
        except Exception:
            continue
        for attr, value in UNIFORM.items():
            assert getattr(cls, attr) == value, (name, attr, getattr(cls, attr))
        m = cls.shutdown_options_map
        rows.append((name, family, cls, m, cfg.get("ssh_svcname", "ssh")))

print("//! GENERATED by the snippet in docs/COMPAT.md deviation 108. Do not edit.")
print("//!")
print("//! One row per name in `distros.OSFAMILIES`, read off a constructed")
print("//! `Distro` object rather than transcribed from its source.")
print()
print(
    "use super::{"
    "Distro, HostnameReader, HostnameWriter, LocaleReader, LocaleWriter, "
    "SystemHostnameReader, TimezoneWriter"
    "};"
)
print("use crate::packages::Manager;")
print()
print("/// Every distro `distros.fetch` can resolve, in `OSFAMILIES` order.")
print("pub static DISTROS: &[Distro] = &[")
for name, family, cls, m, svcname in rows:
    print("    Distro {")
    print("        name: %s," % rs(name))
    print("        osfamily: %s," % rs(cls.osfamily))
    print("        default_owner: %s," % rs(cls.default_owner))
    print("        hostname_conf_fn: %s," % rs(cls.hostname_conf_fn))
    print(
        "        systemd_hostname_conf_fn: %s,"
        % opt(getattr(cls, "systemd_hostname_conf_fn", None))
    )
    print("        hostname_writer: HostnameWriter::%s," % hostname_writer(cls))
    print("        hostname_reader: HostnameReader::%s," % hostname_reader(cls))
    print(
        "        system_hostname_reader: SystemHostnameReader::%s,"
        % system_hostname_reader(cls)
    )
    print("        timezone_writer: TimezoneWriter::%s," % timezone_writer(cls))
    print("        tz_local_fn: %s," % opt(getattr(cls, "tz_local_fn", None)))
    print("        clock_conf_fn: %s," % opt(getattr(cls, "clock_conf_fn", None)))
    print("        locale_writer: LocaleWriter::%s," % locale_writer(cls))
    print("        locale_reader: LocaleReader::%s," % locale_reader(cls))
    print("        locale_conf_fn: %s," % opt(getattr(cls, "locale_conf_fn", None)))
    print(
        "        systemd_locale_conf_fn: %s,"
        % opt(getattr(cls, "systemd_locale_conf_fn", None))
    )
    print("        default_locale: %s," % opt(getattr(cls, "default_locale", None)))
    print("        localhost_ip: %s," % rs(cls._get_localhost_ip()))
    print("        prefer_fqdn: %s," % ("true" if cls.prefer_fqdn else "false"))
    print("        usr_lib_exec: %s," % rs(cls.usr_lib_exec))
    print("        shadow_fn: %s," % rs(cls.shadow_fn))
    print("        ci_sudoers_fn: %s," % rs(cls.ci_sudoers_fn))
    print("        resolve_conf_fn: %s," % rs(cls.resolve_conf_fn))
    print("        pip_package_name: %s," % rs(cls.pip_package_name))
    print("        init_cmd: %s," % slist(cls.init_cmd))
    print("        halt_option: %s," % rs(m["halt"]))
    print("        poweroff_option: %s," % rs(m["poweroff"]))
    print("        reboot_option: %s," % rs(m["reboot"]))
    print("        ssh_svcname: %s," % rs(svcname))
    print("        dhclient_lease_directory: %s," % opt(cls.dhclient_lease_directory))
    print("        dhclient_lease_file_regex: %s," % opt(cls.dhclient_lease_file_regex))
    print(
        "        shadow_empty_locked_passwd_patterns: %s,"
        % slist(cls.shadow_empty_locked_passwd_patterns)
    )
    cfg = json.dumps(cls.renderer_configs, sort_keys=True, separators=(",", ":"))
    # Clippy wants the shortest delimiter that works, and the netplan
    # headers are full of `# ...` comment lines, so `"#` is common.
    hashes = ""
    while '"' + hashes in cfg:
        hashes += "#"
    print('        renderer_configs: r%s"%s"%s,' % (hashes, cfg, hashes))
    print(
        "        waits_for_network: %s,"
        % ("true" if waits_for_network(cls) else "false")
    )
    print(
        "        package_managers: &[%s],"
        % ", ".join(
            "Manager::%s" % m.name.capitalize() for m in cls.package_managers
        )
    )
    print("    },")
print("];")

print()
print("/// Every name `-D` and `system_info.distro` accept, in `OSFAMILIES`")
print("/// order. Longer than [`DISTROS`], because argparse offers names that")
print("/// `distros.fetch` then refuses for want of a module.")
print("pub const NAMES: &[&str] = &[")
for family, names in distros.OSFAMILIES.items():
    for name in names:
        print("    %s," % rs(name))
print("];")
print()
print("/// The `OSFAMILIES` key each name in [`NAMES`] appears under.")
print("pub(crate) static FAMILY_OF: &[(&str, &str)] = &[")
for family, names in distros.OSFAMILIES.items():
    for name in names:
        print("    (%s, %s)," % (rs(name), rs(family)))
print("];")
